// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/transfer/knock.proto

package com.garow.proto.transfer;

public final class KnockOuterClass {
  private KnockOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KnockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.garow.proto.transfer.Knock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string clientHost = 1;</code>
     */
    java.lang.String getClientHost();
    /**
     * <code>string clientHost = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientHostBytes();
  }
  /**
   * <pre>
   * 客户端提供一致与路由一致的主机名
   * </pre>
   *
   * Protobuf type {@code com.garow.proto.transfer.Knock}
   */
  public  static final class Knock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.garow.proto.transfer.Knock)
      KnockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Knock.newBuilder() to construct.
    private Knock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Knock() {
      clientHost_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Knock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              clientHost_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.garow.proto.transfer.KnockOuterClass.internal_static_com_jm_proto_transfer_Knock_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.garow.proto.transfer.KnockOuterClass.internal_static_com_jm_proto_transfer_Knock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.garow.proto.transfer.KnockOuterClass.Knock.class, com.garow.proto.transfer.KnockOuterClass.Knock.Builder.class);
    }

    public static final int CLIENTHOST_FIELD_NUMBER = 1;
    private volatile java.lang.Object clientHost_;
    /**
     * <code>string clientHost = 1;</code>
     */
    public java.lang.String getClientHost() {
      java.lang.Object ref = clientHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientHost_ = s;
        return s;
      }
    }
    /**
     * <code>string clientHost = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientHostBytes() {
      java.lang.Object ref = clientHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientHost_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientHost_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.garow.proto.transfer.KnockOuterClass.Knock)) {
        return super.equals(obj);
      }
      com.garow.proto.transfer.KnockOuterClass.Knock other = (com.garow.proto.transfer.KnockOuterClass.Knock) obj;

      boolean result = true;
      result = result && getClientHost()
          .equals(other.getClientHost());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTHOST_FIELD_NUMBER;
      hash = (53 * hash) + getClientHost().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.garow.proto.transfer.KnockOuterClass.Knock parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.garow.proto.transfer.KnockOuterClass.Knock parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.garow.proto.transfer.KnockOuterClass.Knock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.garow.proto.transfer.KnockOuterClass.Knock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.garow.proto.transfer.KnockOuterClass.Knock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.garow.proto.transfer.KnockOuterClass.Knock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.garow.proto.transfer.KnockOuterClass.Knock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.garow.proto.transfer.KnockOuterClass.Knock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.garow.proto.transfer.KnockOuterClass.Knock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.garow.proto.transfer.KnockOuterClass.Knock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.garow.proto.transfer.KnockOuterClass.Knock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.garow.proto.transfer.KnockOuterClass.Knock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.garow.proto.transfer.KnockOuterClass.Knock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 客户端提供一致与路由一致的主机名
     * </pre>
     *
     * Protobuf type {@code com.garow.proto.transfer.Knock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.garow.proto.transfer.Knock)
        com.garow.proto.transfer.KnockOuterClass.KnockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.garow.proto.transfer.KnockOuterClass.internal_static_com_jm_proto_transfer_Knock_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.garow.proto.transfer.KnockOuterClass.internal_static_com_jm_proto_transfer_Knock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.garow.proto.transfer.KnockOuterClass.Knock.class, com.garow.proto.transfer.KnockOuterClass.Knock.Builder.class);
      }

      // Construct using com.garow.proto.transfer.KnockOuterClass.Knock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        clientHost_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.garow.proto.transfer.KnockOuterClass.internal_static_com_jm_proto_transfer_Knock_descriptor;
      }

      @java.lang.Override
      public com.garow.proto.transfer.KnockOuterClass.Knock getDefaultInstanceForType() {
        return com.garow.proto.transfer.KnockOuterClass.Knock.getDefaultInstance();
      }

      @java.lang.Override
      public com.garow.proto.transfer.KnockOuterClass.Knock build() {
        com.garow.proto.transfer.KnockOuterClass.Knock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.garow.proto.transfer.KnockOuterClass.Knock buildPartial() {
        com.garow.proto.transfer.KnockOuterClass.Knock result = new com.garow.proto.transfer.KnockOuterClass.Knock(this);
        result.clientHost_ = clientHost_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.garow.proto.transfer.KnockOuterClass.Knock) {
          return mergeFrom((com.garow.proto.transfer.KnockOuterClass.Knock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.garow.proto.transfer.KnockOuterClass.Knock other) {
        if (other == com.garow.proto.transfer.KnockOuterClass.Knock.getDefaultInstance()) return this;
        if (!other.getClientHost().isEmpty()) {
          clientHost_ = other.clientHost_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.garow.proto.transfer.KnockOuterClass.Knock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.garow.proto.transfer.KnockOuterClass.Knock) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object clientHost_ = "";
      /**
       * <code>string clientHost = 1;</code>
       */
      public java.lang.String getClientHost() {
        java.lang.Object ref = clientHost_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientHost_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string clientHost = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientHostBytes() {
        java.lang.Object ref = clientHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientHost = 1;</code>
       */
      public Builder setClientHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientHost = 1;</code>
       */
      public Builder clearClientHost() {
        
        clientHost_ = getDefaultInstance().getClientHost();
        onChanged();
        return this;
      }
      /**
       * <code>string clientHost = 1;</code>
       */
      public Builder setClientHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientHost_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.garow.proto.transfer.Knock)
    }

    // @@protoc_insertion_point(class_scope:com.garow.proto.transfer.Knock)
    private static final com.garow.proto.transfer.KnockOuterClass.Knock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.garow.proto.transfer.KnockOuterClass.Knock();
    }

    public static com.garow.proto.transfer.KnockOuterClass.Knock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Knock>
        PARSER = new com.google.protobuf.AbstractParser<Knock>() {
      @java.lang.Override
      public Knock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Knock(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Knock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Knock> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.garow.proto.transfer.KnockOuterClass.Knock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jm_proto_transfer_Knock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jm_proto_transfer_Knock_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-src/main/resources/proto/transfer/knoc" +
      "k.proto\022\025com.garow.proto.transfer\"\033\n\005Knock\022" +
      "\022\n\nclientHost\030\001 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_jm_proto_transfer_Knock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jm_proto_transfer_Knock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jm_proto_transfer_Knock_descriptor,
        new java.lang.String[] { "ClientHost", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
