// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/transfer/toclient.proto

package com.garow.proto.transfer;

public final class Toclient {
  private Toclient() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ToClientOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.garow.proto.transfer.ToClient)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 cmd = 1;</code>
     */
    int getCmd();

    /**
     * <code>repeated string sessionIds = 2;</code>
     */
    java.util.List<java.lang.String>
        getSessionIdsList();
    /**
     * <code>repeated string sessionIds = 2;</code>
     */
    int getSessionIdsCount();
    /**
     * <code>repeated string sessionIds = 2;</code>
     */
    java.lang.String getSessionIds(int index);
    /**
     * <code>repeated string sessionIds = 2;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdsBytes(int index);

    /**
     * <code>bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * <pre>
   *转发给客户端的包
   *cmd:0=转发 1=关闭 2=转发并关闭
   * </pre>
   *
   * Protobuf type {@code com.garow.proto.transfer.ToClient}
   */
  public  static final class ToClient extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.garow.proto.transfer.ToClient)
      ToClientOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ToClient.newBuilder() to construct.
    private ToClient(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ToClient() {
      cmd_ = 0;
      sessionIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ToClient(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              cmd_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                sessionIds_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              sessionIds_.add(s);
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          sessionIds_ = sessionIds_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.garow.proto.transfer.Toclient.internal_static_com_jm_proto_transfer_ToClient_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.garow.proto.transfer.Toclient.internal_static_com_jm_proto_transfer_ToClient_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.garow.proto.transfer.Toclient.ToClient.class, com.garow.proto.transfer.Toclient.ToClient.Builder.class);
    }

    private int bitField0_;
    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>int32 cmd = 1;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    public static final int SESSIONIDS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList sessionIds_;
    /**
     * <code>repeated string sessionIds = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSessionIdsList() {
      return sessionIds_;
    }
    /**
     * <code>repeated string sessionIds = 2;</code>
     */
    public int getSessionIdsCount() {
      return sessionIds_.size();
    }
    /**
     * <code>repeated string sessionIds = 2;</code>
     */
    public java.lang.String getSessionIds(int index) {
      return sessionIds_.get(index);
    }
    /**
     * <code>repeated string sessionIds = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdsBytes(int index) {
      return sessionIds_.getByteString(index);
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != 0) {
        output.writeInt32(1, cmd_);
      }
      for (int i = 0; i < sessionIds_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sessionIds_.getRaw(i));
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sessionIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(sessionIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSessionIdsList().size();
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.garow.proto.transfer.Toclient.ToClient)) {
        return super.equals(obj);
      }
      com.garow.proto.transfer.Toclient.ToClient other = (com.garow.proto.transfer.Toclient.ToClient) obj;

      boolean result = true;
      result = result && (getCmd()
          == other.getCmd());
      result = result && getSessionIdsList()
          .equals(other.getSessionIdsList());
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd();
      if (getSessionIdsCount() > 0) {
        hash = (37 * hash) + SESSIONIDS_FIELD_NUMBER;
        hash = (53 * hash) + getSessionIdsList().hashCode();
      }
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.garow.proto.transfer.Toclient.ToClient parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.garow.proto.transfer.Toclient.ToClient parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.garow.proto.transfer.Toclient.ToClient parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.garow.proto.transfer.Toclient.ToClient parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.garow.proto.transfer.Toclient.ToClient parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.garow.proto.transfer.Toclient.ToClient parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.garow.proto.transfer.Toclient.ToClient parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.garow.proto.transfer.Toclient.ToClient parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.garow.proto.transfer.Toclient.ToClient parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.garow.proto.transfer.Toclient.ToClient parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.garow.proto.transfer.Toclient.ToClient parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.garow.proto.transfer.Toclient.ToClient parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.garow.proto.transfer.Toclient.ToClient prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *转发给客户端的包
     *cmd:0=转发 1=关闭 2=转发并关闭
     * </pre>
     *
     * Protobuf type {@code com.garow.proto.transfer.ToClient}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.garow.proto.transfer.ToClient)
        com.garow.proto.transfer.Toclient.ToClientOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.garow.proto.transfer.Toclient.internal_static_com_jm_proto_transfer_ToClient_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.garow.proto.transfer.Toclient.internal_static_com_jm_proto_transfer_ToClient_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.garow.proto.transfer.Toclient.ToClient.class, com.garow.proto.transfer.Toclient.ToClient.Builder.class);
      }

      // Construct using com.garow.proto.transfer.Toclient.ToClient.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cmd_ = 0;

        sessionIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.garow.proto.transfer.Toclient.internal_static_com_jm_proto_transfer_ToClient_descriptor;
      }

      @java.lang.Override
      public com.garow.proto.transfer.Toclient.ToClient getDefaultInstanceForType() {
        return com.garow.proto.transfer.Toclient.ToClient.getDefaultInstance();
      }

      @java.lang.Override
      public com.garow.proto.transfer.Toclient.ToClient build() {
        com.garow.proto.transfer.Toclient.ToClient result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.garow.proto.transfer.Toclient.ToClient buildPartial() {
        com.garow.proto.transfer.Toclient.ToClient result = new com.garow.proto.transfer.Toclient.ToClient(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.cmd_ = cmd_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          sessionIds_ = sessionIds_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.sessionIds_ = sessionIds_;
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.garow.proto.transfer.Toclient.ToClient) {
          return mergeFrom((com.garow.proto.transfer.Toclient.ToClient)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.garow.proto.transfer.Toclient.ToClient other) {
        if (other == com.garow.proto.transfer.Toclient.ToClient.getDefaultInstance()) return this;
        if (other.getCmd() != 0) {
          setCmd(other.getCmd());
        }
        if (!other.sessionIds_.isEmpty()) {
          if (sessionIds_.isEmpty()) {
            sessionIds_ = other.sessionIds_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSessionIdsIsMutable();
            sessionIds_.addAll(other.sessionIds_);
          }
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.garow.proto.transfer.Toclient.ToClient parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.garow.proto.transfer.Toclient.ToClient) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int cmd_ ;
      /**
       * <code>int32 cmd = 1;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>int32 cmd = 1;</code>
       */
      public Builder setCmd(int value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cmd = 1;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList sessionIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSessionIdsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          sessionIds_ = new com.google.protobuf.LazyStringArrayList(sessionIds_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string sessionIds = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSessionIdsList() {
        return sessionIds_.getUnmodifiableView();
      }
      /**
       * <code>repeated string sessionIds = 2;</code>
       */
      public int getSessionIdsCount() {
        return sessionIds_.size();
      }
      /**
       * <code>repeated string sessionIds = 2;</code>
       */
      public java.lang.String getSessionIds(int index) {
        return sessionIds_.get(index);
      }
      /**
       * <code>repeated string sessionIds = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdsBytes(int index) {
        return sessionIds_.getByteString(index);
      }
      /**
       * <code>repeated string sessionIds = 2;</code>
       */
      public Builder setSessionIds(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSessionIdsIsMutable();
        sessionIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sessionIds = 2;</code>
       */
      public Builder addSessionIds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSessionIdsIsMutable();
        sessionIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sessionIds = 2;</code>
       */
      public Builder addAllSessionIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureSessionIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sessionIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sessionIds = 2;</code>
       */
      public Builder clearSessionIds() {
        sessionIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sessionIds = 2;</code>
       */
      public Builder addSessionIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSessionIdsIsMutable();
        sessionIds_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 3;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.garow.proto.transfer.ToClient)
    }

    // @@protoc_insertion_point(class_scope:com.garow.proto.transfer.ToClient)
    private static final com.garow.proto.transfer.Toclient.ToClient DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.garow.proto.transfer.Toclient.ToClient();
    }

    public static com.garow.proto.transfer.Toclient.ToClient getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ToClient>
        PARSER = new com.google.protobuf.AbstractParser<ToClient>() {
      @java.lang.Override
      public ToClient parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ToClient(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ToClient> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ToClient> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.garow.proto.transfer.Toclient.ToClient getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jm_proto_transfer_ToClient_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jm_proto_transfer_ToClient_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0src/main/resources/proto/transfer/tocl" +
      "ient.proto\022\025com.garow.proto.transfer\"9\n\010ToC" +
      "lient\022\013\n\003cmd\030\001 \001(\005\022\022\n\nsessionIds\030\002 \003(\t\022\014" +
      "\n\004data\030\003 \001(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_jm_proto_transfer_ToClient_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jm_proto_transfer_ToClient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jm_proto_transfer_ToClient_descriptor,
        new java.lang.String[] { "Cmd", "SessionIds", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
