server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        #git:
#          uri: https://github.com/kbastani/spring-boot-microservice-config
         # uri: file:E:\GitHub\spring-boot-microservice-config
        native: 
          searchLocations: classpath:configrepo

logging: 
  file: log/log
  level: 
    ROOT: 'INFO'
  config: classpath:configrepo/logback-dev.xml